"""Routes for reports blueprint."""

from flask import Blueprint, render_template, request, redirect, url_for, session, flash, jsonify, make_response
from models.database import get_db, get_setting
from utils.auth_decorators import login_required, admin_required
from services.fema import lookup_fema_flood_zone
from services.email import send_email
import json
import datetime
import xml.etree.ElementTree as _ET

bp = Blueprint("reports", __name__)

def _build_proof_of_loss_text(claim, rooms, room_data):
    """Generate a plain-text Proof of Loss document pre-filled with claim data."""
    now  = datetime.datetime.now().strftime('%B %d, %Y')
    lines = [
        'PROOF OF LOSS',
        'NATIONAL FLOOD INSURANCE PROGRAM (NFIP)',
        'Standard Flood Insurance Policy',
        '=' * 60,
        '',
        f'Date of Statement:        {now}',
        f'Claim Number:             {claim["claim_number"]}',
        f'Policy Number:            {claim["policy_number"] or "_________________________"}',
        f'Policy Type:              {claim["policy_type"] or "Building + Contents"}',
        f'Insurance Company:        {claim["insurance_company"] or "_________________________"}',
        '',
        'INSURED (POLICYHOLDER)',
        '-' * 40,
        f'Name:                     {claim["client_name"]}',
        f'Phone:                    {claim["client_phone"] or "_________________________"}',
        f'Email:                    {claim["client_email"] or "_________________________"}',
        '',
        'PROPERTY',
        '-' * 40,
        f'Property Address:         {claim["property_address"]}',
        f'Property Type:            {claim["property_type"] or "_________________________"}',
        f'Year Built:               {claim["year_built"] or "_________________________"}',
        f'Square Footage:           {claim["property_sqft"] or "_________________________"}',
        f'FEMA Flood Zone:          {claim["flood_zone"] or "_________________________"}',
        f'FEMA Map Panel Number:    {claim["fema_map_number"] or "_________________________"}',
        '',
        'LOSS INFORMATION',
        '-' * 40,
        f'Date of Loss:             {claim["flood_date"]}',
        f'Cause of Loss:            {claim["flood_source"] or claim["cause_of_loss"] or "Flood"}',
        f'Water Category:           Category {claim["water_category"] or "3"} (Flood water)',
        f'Water Class:              Class {claim["water_class"] or "_"}',
        f'Water Depth (inches):     {claim["water_depth_in"] or "_________________________"}',
        f'Date Water Removed:       {claim["date_water_removed"] or "_________________________"}',
        f'Inspection Date:          {claim["inspection_date"] or "_________________________"}',
        '',
        'COVERAGE',
        '-' * 40,
        f'Building Coverage:        ${claim["coverage_building"]:,.2f}',
        f'Contents Coverage:        ${claim["coverage_contents"]:,.2f}',
        f'Deductible:               ${claim["deductible"]:,.2f}',
        '',
        'MORTGAGE',
        '-' * 40,
        f'Mortgage Company:         {claim["mortgage_company"] or "N/A"}',
        f'Loan Number:              {claim["mortgage_loan_number"] or "N/A"}',
        '',
        'DAMAGE SUMMARY BY ROOM',
        '-' * 40,
    ]
    for rd in room_data:
        room  = rd['room']
        items = rd['line_items']
        lines.append(f'\n  {room["name"]}   Subtotal: ${room["subtotal"]:,.2f}')
        for item in items:
            lines.append(f'    - {item["description"]:40s}  {item["quantity"]} {item["unit"]:8s}  '
                         f'@ ${item["unit_cost"]:8.2f}  =  ${item["total"]:10.2f}')
    lines += [
        '',
        '=' * 60,
        f'TOTAL CLAIM ESTIMATE:     ${claim["total_estimate"]:,.2f}',
        f'Less Deductible:          ${claim["deductible"]:,.2f}',
        f'NET CLAIM AMOUNT:         ${max(0, claim["total_estimate"] - claim["deductible"]):,.2f}',
        '=' * 60,
        '',
        'CERTIFICATION',
        '-' * 40,
        'The insured hereby certifies that the above information is true and',
        'accurate to the best of their knowledge and belief, and that this Proof',
        'of Loss is submitted pursuant to the Standard Flood Insurance Policy.',
        '',
        f'Insured Signature:        _________________________ Date: __________',
        f'Printed Name:             {claim["client_name"]}',
        '',
        f'Adjuster Name:            {claim["adjuster_name"] or "_________________________"}',
        f'Adjuster Signature:       _________________________ Date: __________',
        f'Flood Control Number:     _________________________',
        '',
        '--- Generated by FloodClaims Pro ---',
    ]
    return '\n'.join(lines)




def _build_building_worksheet_text(claim, room_data):
    """Generate NFIP-style Building Property Worksheet."""
    now = datetime.datetime.now().strftime('%B %d, %Y')
    lines = [
        'NFIP BUILDING PROPERTY WORKSHEET',
        '=' * 60,
        f'Claim Number:     {claim["claim_number"]}',
        f'Policy Number:    {claim["policy_number"] or "_________________________"}',
        f'Insured:          {claim["client_name"]}',
        f'Property:         {claim["property_address"]}',
        f'Date of Loss:     {claim["flood_date"]}',
        f'Prepared:         {now}',
        f'Adjuster:         {claim["adjuster_name"] or "_________________________"}',
        '',
        'BUILDING CHARACTERISTICS',
        '-' * 40,
        f'Type:             {claim["property_type"] or "_________________________"}',
        f'Year Built:       {claim["year_built"] or "_________________________"}',
        f'Square Footage:   {claim["property_sqft"] or "_________________________"} sq ft',
        f'Floors:           {claim["num_floors"] or "_________________________"}',
        f'Flood Zone:       {claim["flood_zone"] or "_________________________"}',
        f'FIRM Panel:       {claim["fema_map_number"] or "_________________________"}',
        '',
        'WATER/DAMAGE DETAILS',
        '-' * 40,
        f'Water Source:     {claim["flood_source"] or "Flood"}',
        f'Water Category:   Category {claim["water_category"] or "3"}',
        f'Water Class:      Class {claim["water_class"] or "_"}',
        f'Depth (in):       {claim["water_depth_in"] or "_"}',
        f'Date Removed:     {claim["date_water_removed"] or "_________________________"}',
        '',
        'ROOM-BY-ROOM DAMAGE',
        '-' * 40,
    ]
    for rd in room_data:
        room  = rd['room']
        items = rd['line_items']
        lines.append(f'\nRoom: {room["name"]}  (Subtotal: ${room["subtotal"]:,.2f})')
        lines.append(f'  {"Description":<42} {"Qty":>6} {"Unit":<8} {"Unit $":>9} {"Total":>10}')
        lines.append('  ' + '-' * 78)
        for item in items:
            lines.append(f'  {item["description"]:<42} {item["quantity"]:>6} '
                         f'{item["unit"]:<8} {item["unit_cost"]:>9.2f} {item["total"]:>10.2f}')
    lines += [
        '',
        '=' * 60,
        f'TOTAL BUILDING ESTIMATE:  ${claim["total_estimate"]:,.2f}',
        '=' * 60,
    ]
    return '\n'.join(lines)




def _build_xactimate_esx(claim, rooms_data):
    """Build Xactimate-compatible ESX (XML) content."""
    now = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<XactimateEstimate version="1.0" xmlns="http://www.xactware.com/xactimate">',
        '  <Header>',
        f'    <FileType>ESX</FileType>',
        f'    <CreatedBy>FloodClaims Pro</CreatedBy>',
        f'    <ExportDate>{now}</ExportDate>',
        '  </Header>',
        '  <ClaimInfo>',
        f'    <ClaimNumber>{claim["claim_number"]}</ClaimNumber>',
        f'    <TypeOfLoss>Flood</TypeOfLoss>',
        f'    <DateOfLoss>{claim["flood_date"]}</DateOfLoss>',
        f'    <InsuredName>{claim["client_name"]}</InsuredName>',
        f'    <InsuredPhone>{claim["client_phone"] or ""}</InsuredPhone>',
        f'    <InsuredEmail>{claim["client_email"] or ""}</InsuredEmail>',
        f'    <LossAddress>{claim["property_address"]}</LossAddress>',
        f'    <InsuranceCompany>{claim["insurance_company"] or ""}</InsuranceCompany>',
        f'    <PolicyNumber>{claim["policy_number"] or ""}</PolicyNumber>',
        f'    <PolicyType>{claim["policy_type"] or ""}</PolicyType>',
        f'    <CoverageBuilding>{claim["coverage_building"]:.2f}</CoverageBuilding>',
        f'    <CoverageContents>{claim["coverage_contents"]:.2f}</CoverageContents>',
        f'    <Deductible>{claim["deductible"]:.2f}</Deductible>',
        f'    <FloodZone>{claim["flood_zone"] or ""}</FloodZone>',
        f'    <FIRMPanelNumber>{claim["fema_map_number"] or ""}</FIRMPanelNumber>',
        f'    <WaterCategory>{claim["water_category"] or ""}</WaterCategory>',
        f'    <WaterClass>{claim["water_class"] or ""}</WaterClass>',
        f'    <WaterDepthInches>{claim["water_depth_in"] or ""}</WaterDepthInches>',
        f'    <MortgageCompany>{claim["mortgage_company"] or ""}</MortgageCompany>',
        f'    <MortgageLoanNumber>{claim["mortgage_loan_number"] or ""}</MortgageLoanNumber>',
        f'    <AdjusterName>{claim["adjuster_name"] or ""}</AdjusterName>',
        f'    <TotalEstimate>{claim["total_estimate"]:.2f}</TotalEstimate>',
        '  </ClaimInfo>',
        '  <Rooms>',
    ]
    for rd in rooms_data:
        room  = rd['room']
        items = rd['line_items']
        lines += [
            '    <Room>',
            f'      <Name>{room["name"]}</Name>',
            f'      <Description>{room["description"] or ""}</Description>',
            f'      <Subtotal>{room["subtotal"]:.2f}</Subtotal>',
            '      <LineItems>',
        ]
        for item in items:
            lines += [
                '        <LineItem>',
                f'          <Description>{item["description"]}</Description>',
                f'          <Quantity>{item["quantity"]}</Quantity>',
                f'          <Unit>{item["unit"]}</Unit>',
                f'          <UnitCost>{item["unit_cost"]:.2f}</UnitCost>',
                f'          <Total>{item["total"]:.2f}</Total>',
                '        </LineItem>',
            ]
        lines += ['      </LineItems>', '    </Room>']
    lines += ['  </Rooms>', '</XactimateEstimate>']
    return '\n'.join(lines)




def _build_photo_manifest(claim, room_data, unassigned):
    """Build a plain-text photo manifest listing all photos and their rooms."""
    lines = [
        f'PHOTO MANIFEST',
        f'Claim: {claim["claim_number"]} — {claim["client_name"]}',
        f'Property: {claim["property_address"]}',
        f'Generated: {datetime.datetime.now().strftime("%B %d, %Y %I:%M %p")}',
        '=' * 60, ''
    ]
    total = 0
    for rd in room_data:
        photos = rd.get('room_photos', [])
        if photos:
            lines.append(f'Room: {rd["room"]["name"]} ({len(photos)} photos)')
            for p in photos:
                lines.append(f'  - {p["filename"]}  |  {p["caption"] or "No caption"}')
                if p['ai_description']:
                    lines.append(f'    AI: {p["ai_description"][:120]}')
            total += len(photos)
    if unassigned:
        lines.append(f'Unassigned Photos ({len(unassigned)})')
        for p in unassigned:
            lines.append(f'  - {p["filename"]}  |  {p["caption"] or "No caption"}')
        total += len(unassigned)
    lines += ['', '=' * 60, f'Total Photos: {total}']
    return '\n'.join(lines)




@bp.route('/claims/<int:claim_id>/report/pdf')
@login_required
def report_pdf(claim_id):
    db = get_db()
    claim = db.execute('''SELECT c.*, u.name as adjuster_name, u.email as adjuster_email
        FROM claims c LEFT JOIN users u ON c.adjuster_id=u.id WHERE c.id=?''', (claim_id,)).fetchone()
    if not claim:
        flash('Claim not found.', 'error')
        return redirect(url_for('auth.dashboard'))
    rooms = db.execute('SELECT * FROM rooms WHERE claim_id=? AND deleted_at IS NULL ORDER BY id', (claim_id,)).fetchall()
    room_data = []
    for room in rooms:
        items  = db.execute('SELECT * FROM line_items WHERE room_id=? AND deleted_at IS NULL ORDER BY id', (room['id'],)).fetchall()
        photos = db.execute('SELECT * FROM photos WHERE room_id=? AND deleted_at IS NULL ORDER BY id', (room['id'],)).fetchall()
        room_data.append({'room': room, 'line_items': items, 'room_photos': photos})
    unassigned_photos = db.execute('SELECT * FROM photos WHERE claim_id=? AND room_id IS NULL AND deleted_at IS NULL', (claim_id,)).fetchall()
    recalc_claim(claim_id, get_db)
    claim = db.execute('''SELECT c.*, u.name as adjuster_name, u.email as adjuster_email
        FROM claims c LEFT JOIN users u ON c.adjuster_id=u.id WHERE c.id=?''', (claim_id,)).fetchone()
    signature = db.execute(
        'SELECT * FROM signatures WHERE claim_id=? ORDER BY id DESC LIMIT 1',
        (claim_id,)).fetchone()
    return render_template('report.html', claim=claim, room_data=room_data,
                           unassigned_photos=unassigned_photos, pdf_mode=True, auto_print=True,
                           signature=signature,
                           generated=datetime.datetime.now().strftime('%B %d, %Y %I:%M %p'))


# ── Xactimate ESX Export ──────────────────────────────────────────────────────


@bp.route('/claims/<int:claim_id>/export/xactimate')
@login_required
def export_xactimate(claim_id):
    db = get_db()
    claim = db.execute('SELECT * FROM claims WHERE id=?', (claim_id,)).fetchone()
    if not claim:
        flash('Claim not found.', 'error')
        return redirect(url_for('auth.dashboard'))
    rooms = db.execute('SELECT * FROM rooms WHERE claim_id=? AND deleted_at IS NULL ORDER BY id', (claim_id,)).fetchall()
    now = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<XactimateEstimate version="1.0">',
        '  <ClaimInfo>',
        f'    <ClaimNumber>{claim["claim_number"]}</ClaimNumber>',
        f'    <InsuredName>{claim["client_name"]}</InsuredName>',
        f'    <LossAddress>{claim["property_address"]}</LossAddress>',
        f'    <DateOfLoss>{claim["flood_date"]}</DateOfLoss>',
        f'    <InsuranceCompany>{claim["insurance_company"]}</InsuranceCompany>',
        f'    <PolicyNumber>{claim["policy_number"]}</PolicyNumber>',
        f'    <FloodZone>{claim["flood_zone"]}</FloodZone>',
        f'    <TotalEstimate>{claim["total_estimate"]:.2f}</TotalEstimate>',
        f'    <ExportDate>{now}</ExportDate>',
        '  </ClaimInfo>',
        '  <Rooms>',
    ]
    for room in rooms:
        items = db.execute('SELECT * FROM line_items WHERE room_id=? AND deleted_at IS NULL ORDER BY id', (room['id'],)).fetchall()
        lines += ['    <Room>', f'      <Name>{room["name"]}</Name>',
                  f'      <Subtotal>{room["subtotal"]:.2f}</Subtotal>', '      <LineItems>']
        for item in items:
            lines += ['        <LineItem>',
                      f'          <Description>{item["description"]}</Description>',
                      f'          <Quantity>{item["quantity"]}</Quantity>',
                      f'          <Unit>{item["unit"]}</Unit>',
                      f'          <UnitCost>{item["unit_cost"]:.2f}</UnitCost>',
                      f'          <Total>{item["total"]:.2f}</Total>',
                      '        </LineItem>']
        lines += ['      </LineItems>', '    </Room>']
    lines += ['  </Rooms>', '</XactimateEstimate>']
    resp = make_response('\n'.join(lines))
    resp.headers['Content-Type'] = 'application/xml'
    resp.headers['Content-Disposition'] = f'attachment; filename="{claim["claim_number"]}-xactimate.esx"'
    return resp


# ── FEMA Flood Zone Lookup ────────────────────────────────────────────────────


@bp.route('/claims/<int:claim_id>/fema-lookup', methods=['POST'])
@login_required
def fema_lookup(claim_id):
    db = get_db()
    claim = db.execute('SELECT * FROM claims WHERE id=?', (claim_id,)).fetchone()
    if not claim:
        return jsonify({'error': 'not found'}), 404
    result = lookup_fema_flood_zone(claim['property_address'])
    if result:
        result = dict(result) if not isinstance(result, dict) else result
        db.execute('UPDATE claims SET flood_zone=?,fema_map_number=?,lat=?,lng=?,maps_embed_url=? WHERE id=?',
                   (result.get('flood_zone',''), result.get('fema_map_number',''),
                    result.get('lat',0), result.get('lng',0), result.get('maps_embed_url',''), claim_id))
        db.commit()
    return jsonify({'ok': True, **result})


# ── Client Portal ─────────────────────────────────────────────────────────────


@bp.route('/claims/<int:claim_id>/portal/generate', methods=['POST'])
@login_required
def generate_portal_link(claim_id):
    db = get_db()
    token = secrets.token_urlsafe(24)
    db.execute('DELETE FROM client_portal_tokens WHERE claim_id=?', (claim_id,))
    db.execute('INSERT INTO client_portal_tokens (claim_id, token) VALUES (?,?)', (claim_id, token))
    db.commit()
    portal_url = url_for('client_portal', token=token, _external=True)
    claim = db.execute('SELECT * FROM claims WHERE id=?', (claim_id,)).fetchone()
    if claim['client_email']:
        subject = f'View Your Flood Damage Claim — {claim["claim_number"]}'
        html = f'''<div style="font-family:sans-serif;max-width:600px;margin:0 auto">
            <h2 style="color:#0a1628">Your Claim Portal</h2>
            <p>Hello {claim["client_name"]},</p>
            <p>Your adjuster has shared your flood damage claim with you.</p>
            <p><a href="{portal_url}" style="background:#0a1628;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;display:inline-block;margin:16px 0">View My Claim ↗</a></p>
            <p style="font-size:12px;color:#94a3b8">Claim: {claim["claim_number"]} · FloodClaims Pro</p></div>'''
        send_email(claim['client_email'], subject, html)
    return jsonify({'ok': True, 'portal_url': portal_url, 'token': token})




@bp.route('/portal/<token>')
def client_portal(token):
    db = get_db()
    row = db.execute('SELECT claim_id FROM client_portal_tokens WHERE token=?', (token,)).fetchone()
    if not row:
        return render_template('portal_invalid.html'), 404
    claim_id = row['claim_id']
    claim = db.execute('''SELECT c.*, u.name as adjuster_name, u.email as adjuster_email
        FROM claims c LEFT JOIN users u ON c.adjuster_id=u.id WHERE c.id=?''', (claim_id,)).fetchone()
    rooms = db.execute('SELECT * FROM rooms WHERE claim_id=? AND deleted_at IS NULL ORDER BY id', (claim_id,)).fetchall()
    room_data = []
    for room in rooms:
        items  = db.execute('SELECT * FROM line_items WHERE room_id=? ORDER BY id', (room['id'],)).fetchall()
        photos = db.execute('SELECT * FROM photos WHERE room_id=? AND deleted_at IS NULL ORDER BY id', (room['id'],)).fetchall()
        room_data.append({'room': room, 'line_items': items, 'room_photos': photos})
    return render_template('client_portal.html', claim=claim, room_data=room_data, token=token,
                           generated=datetime.datetime.now().strftime('%B %d, %Y'))


# ── Digital Signature ─────────────────────────────────────────────────────────


@bp.route('/claims/<int:claim_id>/sign', methods=['POST'])
def sign_claim(claim_id):
    data = request.get_json(silent=True) or {}
    signer   = data.get('signer', 'Client').strip()
    sig_data = data.get('sig_data', '').strip()
    if not sig_data:
        return jsonify({'error': 'sig_data required'}), 400
    db = get_db()
    db.execute('DELETE FROM signatures WHERE claim_id=?', (claim_id,))
    db.execute('INSERT INTO signatures (claim_id, signer, sig_data) VALUES (?,?,?)',
               (claim_id, signer, sig_data))
    db.commit()
    return jsonify({'ok': True, 'message': f'Claim signed by {signer}'})




@bp.route('/claims/<int:claim_id>/signature')
@login_required
def get_signature(claim_id):
    db = get_db()
    sig = db.execute('SELECT * FROM signatures WHERE claim_id=? ORDER BY id DESC LIMIT 1', (claim_id,)).fetchone()
    if not sig:
        return jsonify({'signed': False})
    return jsonify({'signed': True, 'signer': sig['signer'], 'signed_at': sig['signed_at']})


# ── Stripe Subscriptions ──────────────────────────────────────────────────────
STRIPE_PLANS = [
    {'id': 'basic',  'name': 'Basic',  'price': '$49/mo',  'price_cents': 4900,
     'stripe_price_id': 'price_1TS3NiE50C70iVkQpmBiiQr0',
     'features': ['25 claims/mo', 'PDF export', 'Aquila AI', 'Client portal', 'NFIP Compliance']},
    {'id': 'pro',    'name': 'Pro',    'price': '$99/mo',  'price_cents': 9900,
     'stripe_price_id': 'price_1TS3NiE50C70iVkQGZYJRdNq',
     'features': ['100 claims/mo', 'Everything in Basic', 'Xactimate export', 'Analytics', 'Priority support']},
    {'id': 'agency', 'name': 'Agency', 'price': '$249/mo', 'price_cents': 24900,
     'stripe_price_id': 'price_1TS3NiE50C70iVkQD6vVFdsV',
     'features': ['Unlimited claims', 'Everything in Pro', 'Multi-adjuster team', 'White-label reports', 'SMS alerts']},
]



@bp.route('/claims/<int:claim_id>/report')
@login_required
def report(claim_id):
    db    = get_db()
    claim = db.execute('''SELECT c.*, u.name as adjuster_name, u.email as adjuster_email
        FROM claims c LEFT JOIN users u ON c.adjuster_id=u.id WHERE c.id=?''',
        (claim_id,)).fetchone()
    if not claim:
        flash('Claim not found.', 'error')
        return redirect(url_for('auth.dashboard'))
    rooms = db.execute('SELECT * FROM rooms WHERE claim_id=? AND deleted_at IS NULL ORDER BY id', (claim_id,)).fetchall()
    room_data = []
    for room in rooms:
        items  = db.execute('SELECT * FROM line_items WHERE room_id=? ORDER BY id', (room['id'],)).fetchall()
        photos = db.execute('SELECT * FROM photos WHERE room_id=? AND deleted_at IS NULL ORDER BY id',     (room['id'],)).fetchall()
        room_data.append({'room': room, 'line_items': items, 'room_photos': photos})
    unassigned_photos = db.execute(
        'SELECT * FROM photos WHERE claim_id=? AND room_id IS NULL AND deleted_at IS NULL', (claim_id,)).fetchall()
    recalc_claim(claim_id, get_db)
    claim = db.execute('''SELECT c.*, u.name as adjuster_name, u.email as adjuster_email
        FROM claims c LEFT JOIN users u ON c.adjuster_id=u.id WHERE c.id=?''',
        (claim_id,)).fetchone()
    signature = db.execute(
        'SELECT * FROM signatures WHERE claim_id=? ORDER BY id DESC LIMIT 1',
        (claim_id,)).fetchone()
    return render_template('report.html', claim=claim, room_data=room_data,
                           unassigned_photos=unassigned_photos, signature=signature,
                           generated=datetime.datetime.now().strftime('%B %d, %Y %I:%M %p'))

# ── Admin: Settings ───────────────────────────────────────────────────────────


