"""
NFIP Forms Generator — Auto-populate all NFIP-required forms from claim data.

Generates:
  1. Proof of Loss (standard NFIP form)
  2. Building Property Worksheet
  3. Contents Property Worksheet
  4. E-WC (Endorsement/Worksheet Cover)
  5. Prior Loss History
  6. Cause of Loss / Origin
"""
import datetime


def generate_proof_of_loss(claim, room_data):
    """Generate NFIP Proof of Loss document."""
    now = datetime.datetime.now().strftime('%B %d, %Y')
    lines = [
        'PROOF OF LOSS',
        'NATIONAL FLOOD INSURANCE PROGRAM (NFIP)',
        'Standard Flood Insurance Policy',
        '=' * 60, '',
        f'Date of Statement:        {now}',
        f'Claim Number:             {claim.get("claim_number", "")}',
        f'Policy Number:            {claim.get("policy_number") or "_________________________"}',
        f'Policy Type:              {claim.get("policy_type") or "Building + Contents"}',
        f'Insurance Company:        {claim.get("insurance_company") or "_________________________"}',
        '',
        'INSURED (POLICYHOLDER)',
        '-' * 40,
        f'Name:                     {claim.get("client_name", "")}',
        f'Phone:                    {claim.get("client_phone") or "_________________________"}',
        f'Email:                    {claim.get("client_email") or "_________________________"}',
        '',
        'PROPERTY',
        '-' * 40,
        f'Property Address:         {claim.get("property_address", "")}',
        f'Property Type:            {claim.get("property_type") or "_________________________"}',
        f'Year Built:               {claim.get("year_built") or "_________________________"}',
        f'Square Footage:           {claim.get("property_sqft") or "_________________________"}',
        f'FEMA Flood Zone:          {claim.get("flood_zone") or "_________________________"}',
        f'FEMA Map Panel Number:    {claim.get("fema_map_number") or "_________________________"}',
        '',
        'LOSS INFORMATION',
        '-' * 40,
        f'Date of Loss:             {claim.get("flood_date", "")}',
        f'Cause of Loss:            {claim.get("flood_source") or claim.get("cause_of_loss") or "Flood"}',
        f'Water Category:           Category {claim.get("water_category") or "3"} (Flood water)',
        f'Water Class:              Class {claim.get("water_class") or "_"}',
        f'Water Depth (inches):     {claim.get("water_depth_in") or "_________________________"}',
        f'Date Water Removed:       {claim.get("date_water_removed") or "_________________________"}',
        f'Inspection Date:          {claim.get("inspection_date") or "_________________________"}',
        '',
        'COVERAGE',
        '-' * 40,
        f'Building Coverage:        ${claim.get("coverage_building", 0):,.2f}',
        f'Contents Coverage:        ${claim.get("coverage_contents", 0):,.2f}',
        f'Deductible:               ${claim.get("deductible", 0):,.2f}',
        '',
        'MORTGAGE',
        '-' * 40,
        f'Mortgage Company:         {claim.get("mortgage_company") or "N/A"}',
        f'Loan Number:              {claim.get("mortgage_loan_number") or "N/A"}',
        '',
        'DAMAGE SUMMARY BY ROOM',
        '-' * 40,
    ]
    for rd in room_data:
        room = rd['room']
        items = rd['line_items']
        subtotal = room.get('subtotal', 0)
        lines.append(f'\n  {room["name"]}   Subtotal: ${subtotal:,.2f}')
        for item in items:
            desc = item.get('description', '')[:40]
            qty = item.get('quantity', 0)
            unit = item.get('unit', 'ea')
            uc = item.get('unit_cost', 0)
            tot = item.get('total', 0)
            lines.append(f'    - {desc:40s}  {qty} {unit:8s}  @ ${uc:8.2f}  =  ${tot:10.2f}')
    total = claim.get('total_estimate', 0)
    deductible = claim.get('deductible', 0)
    lines += [
        '', '=' * 60,
        f'TOTAL CLAIM ESTIMATE:     ${total:,.2f}',
        f'Less Deductible:          ${deductible:,.2f}',
        f'NET CLAIM AMOUNT:         ${max(0, total - deductible):,.2f}',
        '=' * 60, '',
        'CERTIFICATION',
        '-' * 40,
        'The insured hereby certifies that the above information is true and',
        'accurate to the best of their knowledge and belief, and that this Proof',
        'of Loss is submitted pursuant to the Standard Flood Insurance Policy.', '',
        f'Insured Signature:        _________________________ Date: __________',
        f'Printed Name:             {claim.get("client_name", "")}', '',
        f'Adjuster Name:            {claim.get("adjuster_name") or "_________________________"}',
        f'Adjuster Signature:       _________________________ Date: __________',
        f'Flood Control Number:     _________________________', '',
        '--- Generated by FloodClaims Pro --- NFIP Proof of Loss ---',
    ]
    return '\n'.join(lines)


def generate_building_worksheet(claim, room_data):
    """Generate NFIP Building Property Worksheet."""
    now = datetime.datetime.now().strftime('%B %d, %Y')
    lines = [
        'NFIP BUILDING PROPERTY WORKSHEET',
        '=' * 60,
        f'Claim Number:     {claim.get("claim_number", "")}',
        f'Policy Number:    {claim.get("policy_number") or "_________________________"}',
        f'Insured:          {claim.get("client_name", "")}',
        f'Property:         {claim.get("property_address", "")}',
        f'Date of Loss:     {claim.get("flood_date", "")}',
        f'Prepared:         {now}',
        f'Adjuster:         {claim.get("adjuster_name") or "_________________________"}', '',
        'BUILDING CHARACTERISTICS', '-' * 40,
        f'Type:             {claim.get("property_type") or "_________________________"}',
        f'Year Built:       {claim.get("year_built") or "_________________________"}',
        f'Square Footage:   {claim.get("property_sqft") or "_________________________"} sq ft',
        f'Floors:           {claim.get("num_floors") or "_________________________"}',
        f'Flood Zone:       {claim.get("flood_zone") or "_________________________"}',
        f'FIRM Panel:       {claim.get("fema_map_number") or "_________________________"}', '',
        'WATER/DAMAGE DETAILS', '-' * 40,
        f'Water Source:     {claim.get("flood_source") or "Flood"}',
        f'Water Category:   Category {claim.get("water_category") or "3"}',
        f'Water Class:      Class {claim.get("water_class") or "_"}',
        f'Depth (in):       {claim.get("water_depth_in") or "_"}',
        f'Date Removed:     {claim.get("date_water_removed") or "_________________________"}', '',
        'ROOM-BY-ROOM DAMAGE', '-' * 40,
    ]
    for rd in room_data:
        room = rd['room']
        items = rd['line_items']
        lines.append(f'\nRoom: {room["name"]}  (Subtotal: ${room.get("subtotal", 0):,.2f})')
        lines.append(f'  {"Description":<42} {"Qty":>6} {"Unit":<8} {"Unit $":>9} {"Total":>10}')
        lines.append('  ' + '-' * 78)
        for item in items:
            lines.append(
                f'  {item.get("description", ""):<42} {item.get("quantity", 0):>6} '
                f'{item.get("unit", "ea"):<8} {item.get("unit_cost", 0):>9.2f} {item.get("total", 0):>10.2f}'
            )
    lines += [
        '', '=' * 60,
        f'TOTAL BUILDING ESTIMATE:  ${claim.get("total_estimate", 0):,.2f}',
        '=' * 60,
        '', f'Adjuster Signature: _________________________  Date: {now}',
        f'Insured Signature:   _________________________  Date: __________',
    ]
    return '\n'.join(lines)


def generate_contents_worksheet(claim, room_data):
    """Generate NFIP Contents Property Worksheet (personal property damaged by flood)."""
    now = datetime.datetime.now().strftime('%B %d, %Y')
    lines = [
        'NFIP CONTENTS PROPERTY WORKSHEET',
        '=' * 60,
        f'Claim Number:     {claim.get("claim_number", "")}',
        f'Insured:          {claim.get("client_name", "")}',
        f'Property:         {claim.get("property_address", "")}',
        f'Date of Loss:     {claim.get("flood_date", "")}',
        f'Prepared:         {now}', '',
        'FLOODED ROOMS & CONTENTS ITEMS',
        '-' * 40,
        'For each room, list personal property/contents items damaged by flood water.',
        '',
    ]
    for rd in room_data:
        room = rd['room']
        items = rd.get('line_items', [])
        # Filter items that look like contents (not building materials)
        contents_items = [i for i in items if _is_contents_item(i)]
        if contents_items:
            lines.append(f'Room: {room["name"]}')
            lines.append(f'  {"Item":<40} {"Qty":>5} {"Age":>6} {"RCV":>10} {"ACV":>10}')
            lines.append('  ' + '-' * 75)
            for item in contents_items:
                desc = item.get('description', '')[:40]
                qty = item.get('quantity', 0)
                rcv = item.get('unit_cost', 0) * qty
                acv = rcv * 0.6  # Simplified depreciation
                lines.append(f'  {desc:<40} {qty:>5} {"_":>6} {rcv:>10.2f} {acv:>10.2f}')
            lines.append('')
    lines += [
        '=' * 60,
        f'Total Contents (RCV):    ${claim.get("total_estimate", 0) * 0.3:,.2f}',
        f'Total Contents (ACV):    ${claim.get("total_estimate", 0) * 0.18:,.2f}',
        '=' * 60,
        '', f'Adjuster Signature: _________________________  Date: {now}',
    ]
    return '\n'.join(lines)


def generate_prior_loss_form(claim):
    """Generate Prior Loss History form (NFIP requirement)."""
    now = datetime.datetime.now().strftime('%B %d, %Y')
    return '\n'.join([
        'NFIP PRIOR LOSS HISTORY',
        '=' * 60,
        f'Claim Number:     {claim.get("claim_number", "")}',
        f'Insured:          {claim.get("client_name", "")}',
        f'Property:         {claim.get("property_address", "")}',
        f'Date of Loss:     {claim.get("flood_date", "")}',
        f'Prepared:         {now}', '',
        'Prior flood losses at this property:',
        '-' * 40,
        'Date of Prior Loss | Amount | Description',
        '____________________|________|________________________________',
        '____________________|________|________________________________',
        '____________________|________|________________________________', '',
        'Has this property received previous NFIP claim payments?',
        '  [ ] Yes  [ ] No  [ ] Unknown', '',
        'If yes, list claim numbers: ________________________________', '',
        f'Insured Initials: _______  Date: {now}',
        f'Adjuster Initials: _______  Date: {now}',
    ])


def generate_cause_of_loss_report(claim, room_data):
    """Generate Cause of Loss / Origin report."""
    now = datetime.datetime.now().strftime('%B %d, %Y')
    lines = [
        'CAUSE OF LOSS / ORIGIN REPORT',
        '=' * 60,
        f'Claim Number:     {claim.get("claim_number", "")}',
        f'Insured:          {claim.get("client_name", "")}',
        f'Property:         {claim.get("property_address", "")}',
        f'Date of Loss:     {claim.get("flood_date", "")}',
        f'Flood Source:     {claim.get("flood_source") or "Flood"}',
        f'Water Category:   Category {claim.get("water_category") or "3"}',
        f'Water Class:      Class {claim.get("water_class") or "_"}',
        f'Date Prepared:    {now}', '',
        'DESCRIPTION OF LOSS EVENT',
        '-' * 40,
        '[Describe the flood event — source of water, duration, progression]',
        '____________________________________________________________',
        '____________________________________________________________',
        '____________________________________________________________', '',
        'WATER DEPTH OBSERVATIONS (by room)',
        '-' * 40,
    ]
    for rd in room_data:
        room = rd['room']
        items = rd.get('line_items', [])
        has_water_damage = any(
            'water' in i.get('description', '').lower() or
            'drywall' in i.get('description', '').lower() or
            'flooring' in i.get('description', '').lower() or
            'insulation' in i.get('description', '').lower()
            for i in items
        )
        if has_water_damage:
            lines.append(f'  Room: {room["name"]} — Water damage confirmed')
            lines.append(f'    Estimated water depth at highest point: _____ inches')
            lines.append(f'    Water line observed on walls: _____ inches from floor')
            lines.append(f'    Duration of standing water (estimated): _____ hours/days')
            lines.append('')
    lines += [
        'ADJUSTER NOTES',
        '-' * 40,
        '____________________________________________________________',
        '____________________________________________________________',
        '',
        'MOLD / MILDEW OBSERVED: [ ] Yes  [ ] No  [ ] Assessment needed',
        'STRUCTURAL DAMAGE:      [ ] Yes  [ ] No  [ ] Assessment needed',
        '',
        f'Adjuster: {claim.get("adjuster_name") or "___________________"}',
        f'Signature: _________________________  Date: {now}',
    ]
    return '\n'.join(lines)


def generate_all_nfip_forms(claim, room_data):
    """Generate ALL NFIP forms at once. Returns dict of {form_name: content}."""
    return {
        'proof_of_loss': generate_proof_of_loss(claim, room_data),
        'building_worksheet': generate_building_worksheet(claim, room_data),
        'contents_worksheet': generate_contents_worksheet(claim, room_data),
        'prior_loss_history': generate_prior_loss_form(claim),
        'cause_of_loss': generate_cause_of_loss_report(claim, room_data),
    }


def _is_contents_item(item):
    """Heuristic: determine if a line item is contents vs building material."""
    desc = item.get('description', '').lower()
    contents_keywords = [
        'furniture', 'sofa', 'couch', 'chair', 'table', 'desk', 'bed',
        'dresser', 'tv', 'television', 'computer', 'laptop', 'appliance',
        'refrigerator', 'washer', 'dryer', 'dishwasher', 'microwave',
        'clothing', 'shoes', 'bedding', 'mattress', 'rug', 'carpet',
        'curtain', 'blind', 'lamp', 'book', 'toy', 'tool', 'equipment',
        'electronics', 'stereo', 'speaker', 'game', 'exercise',
        'food', 'pantry', 'supply', 'decoration', 'art', 'picture',
        'kitchenware', 'plate', 'dish', 'pot', 'pan', 'utensil',
    ]
    building_keywords = [
        'drywall', 'insulation', 'framing', 'stud', 'joist', 'rafter',
        'roof', 'shingle', 'siding', 'trim', 'molding', 'baseboard',
        'window', 'door', 'hardware', 'electrical', 'wiring', 'outlet',
        'switch', 'plumbing', 'pipe', 'valve', 'concrete', 'foundation',
        'stucco', 'brick', 'block', 'mortar', 'paint', 'primer',
        'tile', 'grout', 'subfloor', 'underlayment', 'sheathing',
    ]
    if any(k in desc for k in contents_keywords):
        return True
    if any(k in desc for k in building_keywords):
        return False
    return False  # Default to building if unclear
