"""
Supplement Generator — One-click supplemental claim creation.

A supplemental claim is submitted when:
  1. Additional damage is discovered after initial submission
  2. Carrier's scope/estimate is insufficient
  3. Hidden damage found during repairs
  4. Code upgrades required
  5. Betterment / matching issues
"""
import datetime
import json


def generate_supplement_data(claim_id, claim, room_data, supplement_items, reason='additional_damage'):
    """
    Generate complete supplement package.

    Args:
        claim_id: Claim ID
        claim: Claim dict from DB
        room_data: Current room/line item data
        supplement_items: List of new/modified items, each:
            {'room_name': str, 'description': str, 'quantity': float,
             'unit': str, 'unit_cost': float, 'reason': str}
        reason: One of 'additional_damage', 'carrier_underpaid', 'hidden_damage',
                'code_upgrade', 'matching', 'betterment'

    Returns:
        Dict with supplement text, comparison data, and totals
    """
    reason_labels = {
        'additional_damage': 'Additional Damage Discovered',
        'carrier_underpaid': 'Carrier Estimate Insufficient',
        'hidden_damage': 'Hidden Damage Found During Repairs',
        'code_upgrade': 'Building Code Upgrade Required',
        'matching': 'Matching / Betterment',
        'betterment': 'Betterment Adjustment',
    }

    now = datetime.datetime.now().strftime('%B %d, %Y')
    original_total = claim.get('total_estimate', 0)

    # Build supplement line items
    supplement_room_data = []
    supplement_total = 0
    items_by_room = {}

    for item in supplement_items:
        room_name = item.get('room_name', 'General')
        if room_name not in items_by_room:
            items_by_room[room_name] = []
        total = item.get('quantity', 0) * item.get('unit_cost', 0)
        item['total'] = total
        items_by_room[room_name].append(item)
        supplement_total += total

    for room_name, items in items_by_room.items():
        room_subtotal = sum(i.get('total', 0) for i in items)
        supplement_room_data.append({
            'room': {'name': room_name, 'subtotal': room_subtotal},
            'line_items': items,
        })

    # Build the supplement text
    lines = [
        'SUPPLEMENTAL CLAIM',
        'NATIONAL FLOOD INSURANCE PROGRAM (NFIP)',
        '=' * 60, '',
        f'Original Claim Number:    {claim.get("claim_number", "")}',
        f'Supplement Date:          {now}',
        f'Supplement Reason:        {reason_labels.get(reason, reason)}',
        f'Insured:                  {claim.get("client_name", "")}',
        f'Property:                 {claim.get("property_address", "")}',
        f'Date of Loss:             {claim.get("flood_date", "")}',
        f'Insurance Company:        {claim.get("insurance_company") or "N/A"}',
        f'Policy Number:            {claim.get("policy_number") or "N/A"}',
        '',
        'JUSTIFICATION',
        '-' * 40,
        _get_justification_text(reason),
        '',
        'SUPPLEMENTAL ITEMS (Not Included in Original Estimate)',
        '-' * 40,
    ]

    for rd in supplement_room_data:
        room = rd['room']
        items = rd['line_items']
        lines.append(f'\n  {room["name"]}   Supplement Subtotal: ${room["subtotal"]:,.2f}')
        for item in items:
            desc = item.get('description', '')[:40]
            qty = item.get('quantity', 0)
            unit = item.get('unit', 'ea')
            uc = item.get('unit_cost', 0)
            tot = item.get('total', 0)
            item_reason = item.get('reason', '')
            lines.append(f'    - {desc:40s}  {qty} {unit:8s}  @ ${uc:8.2f}  =  ${tot:10.2f}')
            if item_reason:
                lines.append(f'      Reason: {item_reason}')

    revised_total = original_total + supplement_total
    lines += [
        '',
        '=' * 60,
        f'Original Estimate:        ${original_total:,.2f}',
        f'Supplement Amount:        ${supplement_total:,.2f}',
        f'REVISED TOTAL ESTIMATE:   ${revised_total:,.2f}',
        '=' * 60, '',
        f'Additional amount requested: ${supplement_total:,.2f}',
        '',
        f'Insured Signature:        _________________________  Date: __________',
        f'Adjuster Signature:       _________________________  Date: {now}',
        f'Flood Control Number:     _________________________',
        '',
        '--- Generated by FloodClaims Pro --- Supplemental Claim ---',
    ]

    # Build comparison table (original vs supplement)
    comparison = {
        'original_total': original_total,
        'supplement_total': supplement_total,
        'revised_total': revised_total,
        'supplement_items_count': len(supplement_items),
        'original_rooms': len(room_data),
        'supplement_rooms': len(supplement_room_data),
    }

    return {
        'supplement_text': '\n'.join(lines),
        'comparison': comparison,
        'supplement_room_data': supplement_room_data,
        'supplement_total': supplement_total,
        'revised_total': revised_total,
        'reason': reason,
        'reason_label': reason_labels.get(reason, reason),
        'generated_at': now,
    }


def generate_comparison_report(original_data, supplement_data):
    """
    Generate a side-by-side comparison of original estimate vs supplement.

    Args:
        original_data: Dict with original room_data and total
        supplement_data: Output from generate_supplement_data()

    Returns:
        Formatted comparison text
    """
    now = datetime.datetime.now().strftime('%B %d, %Y')
    lines = [
        'ESTIMATE COMPARISON REPORT',
        '=' * 60,
        f'Date: {now}',
        '',
        f'{"Description":<40} {"Original":>12} {"Supplement":>12} {"Revised":>12}',
        '-' * 76,
    ]

    # Group original by room
    original_by_room = {}
    for rd in original_data.get('room_data', []):
        room_name = rd['room']['name']
        original_by_room[room_name] = rd['room'].get('subtotal', 0)

    # Get supplement rooms
    supplement_rooms = {}
    for rd in supplement_data.get('supplement_room_data', []):
        room_name = rd['room']['name']
        supplement_rooms[room_name] = rd['room'].get('subtotal', 0)

    all_rooms = list(set(list(original_by_room.keys()) + list(supplement_rooms.keys())))
    for room in sorted(all_rooms):
        orig = original_by_room.get(room, 0)
        supp = supplement_rooms.get(room, 0)
        revised = orig + supp
        lines.append(f'  {room:<38} ${orig:>10,.2f} ${supp:>10,.2f} ${revised:>10,.2f}')

    lines += [
        '-' * 76,
        f'  {"TOTALS":<38} ${original_data.get("total", 0):>10,.2f} '
        f'${supplement_data.get("supplement_total", 0):>10,.2f} '
        f'${supplement_data.get("revised_total", 0):>10,.2f}',
        '=' * 76,
    ]
    return '\n'.join(lines)


def suggest_supplement_items(claim, room_data, ai_photo_descriptions=None):
    """
    AI-assisted supplement suggestions.
    Analyzes claim data and photo descriptions to suggest potential supplement items.

    Args:
        claim: Claim dict
        room_data: Room/line items data
        ai_photo_descriptions: Dict of photo_id -> AI description text

    Returns:
        List of suggested supplement items with explanations
    """
    suggestions = []

    # Check for common flood damage items that are often missed
    all_item_descriptions = set()
    for rd in room_data:
        for item in rd['line_items']:
            all_item_descriptions.add(item.get('description', '').lower())

    # Common missed items in flood claims
    common_missed = [
        {
            'category': 'Antimicrobial Treatment',
            'items': ['antimicrobial', 'disinfectant', 'sanitizer'],
            'description': 'Antimicrobial treatment for all flooded rooms',
            'reason': 'NFIP requires antimicrobial treatment for all Category 2+ water',
            'est_cost_per_sf': 0.50,
        },
        {
            'category': 'Moisture Mapping',
            'items': ['moisture map', 'moisture reading'],
            'description': 'Moisture mapping and documentation',
            'reason': 'Required for NFIP compliance — documents extent of water damage',
            'est_flat_cost': 250.00,
        },
        {
            'category': 'Dumpster / Debris Removal',
            'items': ['dumpster', 'debris removal', 'trash', 'haul away'],
            'description': 'Dumpster for demolition debris removal',
            'reason': 'Often omitted from initial estimates — required for tear-out debris',
            'est_flat_cost': 450.00,
        },
        {
            'category': 'Content Manipulation',
            'items': ['content manipulation', 'content move', 'pack out'],
            'description': 'Content manipulation to access damaged building materials',
            'reason': 'Needed to remove and protect personal property before repairs',
            'est_cost_per_sf': 2.00,
        },
        {
            'category': 'Mold Remediation',
            'items': ['mold', 'remediation', 'encapsulation'],
            'description': 'Mold remediation assessment and treatment',
            'reason': 'Required if water stood >48 hours or visible mold present',
            'est_cost_per_sf': 20.00,
        },
        {
            'category': 'Re-inspection',
            'items': ['re-inspection', 'reinspect', 'electrical inspection'],
            'description': 'Electrical re-inspection after flood damage',
            'reason': 'Required by code after water contact with electrical systems',
            'est_flat_cost': 200.00,
        },
    ]

    sqft_str = claim.get('property_sqft', '0')
    try:
        sqft = float(sqft_str) if sqft_str else 1000
    except (ValueError, TypeError):
        sqft = 1000

    for check in common_missed:
        already_included = any(
            any(item_keyword in existing for item_keyword in check['items'])
            for existing in all_item_descriptions
        )
        if not already_included:
            est_cost = check.get('est_flat_cost')
            if est_cost is None:
                est_cost = check.get('est_cost_per_sf', 0) * sqft
            suggestions.append({
                'category': check['category'],
                'description': check['description'],
                'reason': check['reason'],
                'estimated_cost': round(est_cost, 2),
                'priority': 'HIGH' if 'mold' in check['category'].lower() or 'antimicrobial' in check['category'].lower() else 'MEDIUM',
            })

    # Check photo descriptions for missed damage
    if ai_photo_descriptions:
        mold_photos = []
        for pid, desc in ai_photo_descriptions.items():
            desc_lower = desc.lower()
            if 'mold' in desc_lower or 'mildew' in desc_lower:
                mold_photos.append(pid)
            if 'water line' in desc_lower and 'antimicrobial' not in str(all_item_descriptions):
                # Check if water lines are documented
                pass

        if mold_photos and not any('mold' in s['category'].lower() for s in suggestions):
            suggestions.append({
                'category': 'Mold (Photos Detected)',
                'description': f'Mold/mildew detected in {len(mold_photos)} photo(s) — remediation required',
                'reason': 'AI photo analysis detected mold — NFIP requires remediation',
                'estimated_cost': round(sqft * 20.0, 2),
                'priority': 'URGENT',
                'photos_affected': mold_photos,
            })

    return suggestions


def _get_justification_text(reason):
    """Get standard justification text for supplement reason."""
    texts = {
        'additional_damage': (
            'Additional damage was discovered during the inspection process that was not '
            'included in the original estimate. This supplemental documentation identifies '
            'and quantifies the additional scope of work required to restore the property to '
            'pre-loss condition.'
        ),
        'carrier_underpaid': (
            'The original estimate submitted by the carrier does not adequately address the '
            'full scope of flood damage to the insured property. This supplemental claim '
            'provides detailed documentation of the additional work required and associated costs.'
        ),
        'hidden_damage': (
            'During the repair/demolition process, additional hidden flood damage was discovered '
            'that was not visible during the initial inspection. This supplemental claim documents '
            'the newly discovered damage and associated repair costs.'
        ),
        'code_upgrade': (
            'Current building codes require upgrades to the damaged systems that exceed the '
            'pre-loss condition. This supplemental claim documents the code-required upgrades '
            'and associated costs as required by NFIP policy.'
        ),
        'matching': (
            'Due to matching requirements, the undamaged portions of the property must be '
            'replaced/repaired contiguously to ensure a uniform appearance as required by '
            'the Standard Flood Insurance Policy.'
        ),
        'betterment': (
            'Adjustments for betterment are being claimed where the repair/restoration results '
            'in property that is better than pre-loss condition.'
        ),
    }
    return texts.get(reason, 'Supplemental claim submitted for additional documented damage.')
